name: CI com Make

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: sudo apt update && sudo apt install build-essential -y

    - name: Compilar com Make
      run: make

    - name: Rodar testes
      run: make test

    - name: Limpar arquivos gerados
      run: make clean
