name: Build e GIF com Make

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Instalar dependências (build tools + ffmpeg)
      run: sudo apt update && sudo apt install build-essential ffmpeg -y

    - name: Compilar projeto
      run: make

    - name: Rodar testes
      run: make test

    - name: Gerar GIF
      run: make gif

    - name: Limpar arquivos
      run: make clean
